version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./users-db/
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./users-service/
    volumes:
      - './users-service:/usr/src/app'
    ports:
      - '5001' # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    command: gunicorn -b 0.0.0.0:5001 manage:app
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
  webapp:
    container_name: webapp
    build:
      context: ./webapp/
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
    volumes:
      - './webapp/src:/usr/src/app/src'
    ports:
      - '9000:3000' # expose ports - HOST:CONTAINER
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service
  products-service:
    container_name: products-service
    build:
      context: ./products-service/
      args:
        - NODE_ENV=dev
    ports:
      - '5000:5000'
    depends_on:
      - products-db
    links:
      - products-db
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
      - webapp
      - products-service
    links:
      - users-service
      - webapp
  products-db:
    container_name: products-db
    build: ./products-db/
